#define WIFI_SSID "YOUR_WIFI"

#define WIFI_PASSWORD "YOUR_PASSWORD"

#define API_KEY "YOUR_API_KEY"

#define DATABASE_URL "YOUR_DATABASE_URL"

#define BLYNK_AUTH_TOKEN "YOUR_BLYNK_TOKEN"
#define BLYNK_TEMPLATE_ID "YOUR_BLYNK_TEMPLATE_ID"
#define BLYNK_TEMPLATE_NAME "YOUR_BLYNK_TEMPLATE_NAME"


String scriptURL =
"YOUR_SCRIPT_URL";